// Auto-generated by scripts/generate-site-assets.mjs - DO NOT EDIT
export const productData = {
  "brand": {
    "id": "hearthcode-theme",
    "name": "HearthCode Theme",
    "displayName": "HearthCode Theme",
    "summary": "A theme family for code interfaces."
  },
  "product": {
    "id": "hearthcode",
    "name": "HearthCode",
    "displayName": "HearthCode Theme",
    "summary": "A low-glare theme family for code interfaces.",
    "author": {
      "name": "HearthCode",
      "url": "https://theme.hearthcode.dev"
    },
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "scheme": {
    "id": "hearth",
    "name": "HearthCode",
    "headline": "Warm-neutral code color language"
  },
  "flavors": [
    {
      "id": "hearth",
      "name": "HearthCode",
      "shortName": "Ember",
      "pickerName": "Ember",
      "themePrefix": "HearthCode Ember",
      "previewPrefix": "Ember",
      "wordmark": {
        "full": "HearthCode",
        "primary": "Hearth",
        "secondary": "Code"
      },
      "headline": "Warm-neutral code color language",
      "summary": "A warm ember-paper color philosophy for code interfaces.",
      "defaultVariant": "dark",
      "isDefault": true,
      "isActive": true,
      "isPublished": true
    },
    {
      "id": "signal",
      "name": "Moss",
      "shortName": "Moss",
      "pickerName": "Moss",
      "themePrefix": "HearthCode Moss",
      "previewPrefix": "Moss",
      "wordmark": {
        "full": "Moss",
        "primary": "Moss",
        "secondary": ""
      },
      "headline": "Yellow-green paper color language",
      "summary": "A dry yellow-green palette for code interfaces.",
      "defaultVariant": "dark",
      "isDefault": false,
      "isActive": false,
      "isPublished": true
    }
  ],
  "themes": [
    {
      "id": "hearth-dark",
      "schemeId": "hearth",
      "variantId": "dark",
      "flavorLabel": "Ember",
      "climateLabel": "Dark",
      "label": "HearthCode Ember Dark",
      "tabLabel": "Ember Dark",
      "summary": "Warm charcoal.",
      "uiTheme": "vs-dark",
      "path": "./themes/hearth-dark.json",
      "isDefaultTheme": true,
      "isDark": true
    },
    {
      "id": "hearth-light",
      "schemeId": "hearth",
      "variantId": "light",
      "flavorLabel": "Ember",
      "climateLabel": "Light",
      "label": "HearthCode Ember Light",
      "tabLabel": "Ember Light",
      "summary": "Warm paper.",
      "uiTheme": "vs",
      "path": "./themes/hearth-light.json",
      "isDefaultTheme": false,
      "isDark": false
    },
    {
      "id": "signal-dark",
      "schemeId": "signal",
      "variantId": "dark",
      "flavorLabel": "Moss",
      "climateLabel": "Dark",
      "label": "HearthCode Moss Dark",
      "tabLabel": "Moss Dark",
      "summary": "Dry charcoal.",
      "uiTheme": "vs-dark",
      "path": "./themes/signal-dark.json",
      "isDefaultTheme": false,
      "isDark": true
    },
    {
      "id": "signal-light",
      "schemeId": "signal",
      "variantId": "light",
      "flavorLabel": "Moss",
      "climateLabel": "Light",
      "label": "HearthCode Moss Light",
      "tabLabel": "Moss Light",
      "summary": "Dry paper.",
      "uiTheme": "vs",
      "path": "./themes/signal-light.json",
      "isDefaultTheme": false,
      "isDark": false
    }
  ],
  "site": {
    "titleSuffix": "HearthCode",
    "titleDescriptor": "Color Language for Code Interfaces",
    "defaultTitle": "HearthCode — Color Language for Code Interfaces",
    "authorName": "HearthCode",
    "metaPrefix": "hearthcode",
    "hostLabel": "theme.hearthcode.dev",
    "ogImagePath": "/og-hearth.png",
    "ogImageAlt": "HearthCode Theme preview",
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "release": {
    "version": "1.1.4"
  },
  "extension": {
    "itemName": "hearth-code.hearth-theme",
    "previewThemeLabel": "HearthCode Ember Dark",
    "themeCatalog": [
      {
        "variantId": "dark",
        "schemeId": "hearth",
        "flavorLabel": "Ember",
        "climateLabel": "Dark",
        "label": "HearthCode Ember Dark",
        "tabLabel": "Ember Dark",
        "uiTheme": "vs-dark",
        "path": "./themes/hearth-dark.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "darkSoft",
        "schemeId": "hearth",
        "flavorLabel": "Ember",
        "climateLabel": "Dark Soft",
        "label": "HearthCode Ember Dark Soft",
        "tabLabel": "Ember Dark Soft",
        "uiTheme": "vs-dark",
        "path": "./themes/hearth-dark-soft.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "light",
        "schemeId": "hearth",
        "flavorLabel": "Ember",
        "climateLabel": "Light",
        "label": "HearthCode Ember Light",
        "tabLabel": "Ember Light",
        "uiTheme": "vs",
        "path": "./themes/hearth-light.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "lightSoft",
        "schemeId": "hearth",
        "flavorLabel": "Ember",
        "climateLabel": "Light Soft",
        "label": "HearthCode Ember Light Soft",
        "tabLabel": "Ember Light Soft",
        "uiTheme": "vs",
        "path": "./themes/hearth-light-soft.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "dark",
        "schemeId": "signal",
        "flavorLabel": "Moss",
        "climateLabel": "Dark",
        "label": "HearthCode Moss Dark",
        "tabLabel": "Moss Dark",
        "uiTheme": "vs-dark",
        "path": "./themes/signal-dark.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": true
      },
      {
        "variantId": "darkSoft",
        "schemeId": "signal",
        "flavorLabel": "Moss",
        "climateLabel": "Dark Soft",
        "label": "HearthCode Moss Dark Soft",
        "tabLabel": "Moss Dark Soft",
        "uiTheme": "vs-dark",
        "path": "./themes/signal-dark-soft.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": true
      },
      {
        "variantId": "light",
        "schemeId": "signal",
        "flavorLabel": "Moss",
        "climateLabel": "Light",
        "label": "HearthCode Moss Light",
        "tabLabel": "Moss Light",
        "uiTheme": "vs",
        "path": "./themes/signal-light.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": true
      },
      {
        "variantId": "lightSoft",
        "schemeId": "signal",
        "flavorLabel": "Moss",
        "climateLabel": "Light Soft",
        "label": "HearthCode Moss Light Soft",
        "tabLabel": "Moss Light Soft",
        "uiTheme": "vs",
        "path": "./themes/signal-light-soft.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": true
      }
    ]
  },
  "links": {
    "websiteUrl": "https://theme.hearthcode.dev",
    "marketplaceUrl": "https://marketplace.visualstudio.com/items?itemName=hearth-code.hearth-theme",
    "openVsxUrl": "https://open-vsx.org/extension/hearth-code/hearth-theme",
    "vscodeDevUrl": "https://vscode.dev/theme/hearth-code.hearth-theme/HearthCode%20Ember%20Dark",
    "repositoryUrl": "https://github.com/hearth-code/HearthTheme",
    "issuesUrl": "https://github.com/hearth-code/HearthTheme/issues",
    "releasesUrl": "https://github.com/hearth-code/HearthTheme/releases",
    "changelogUrl": "https://github.com/hearth-code/HearthTheme/blob/main/extension/CHANGELOG.md",
    "licenseUrl": "https://github.com/hearth-code/HearthTheme/blob/main/LICENSE",
    "docsRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs",
    "repoBlobRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main",
    "repoTreeRootUrl": "https://github.com/hearth-code/HearthTheme/tree/main",
    "philosophyUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/philosophy.md",
    "schemeUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/scheme.json",
    "specUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-spec.md",
    "baselineUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/theme-baseline.md",
    "tuningUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-system-tuning.md",
    "reportUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-report.md",
    "contractChecklistUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-checklist.md",
    "contractReviewUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-review.md",
    "sourceColorSystemUrl": "https://github.com/hearth-code/HearthTheme/tree/main/color-system",
    "docsEnUrl": "https://theme.hearthcode.dev/docs",
    "docsZhUrl": "https://theme.hearthcode.dev/zh/docs",
    "docsJaUrl": "https://theme.hearthcode.dev/ja/docs"
  }
} as const
