// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT
export const tokens = {
  "dark": {
    "bg": "#161411",
    "fg": "#d6cab4",
    "lineBg": "#1d1a15",
    "lineNo": "#4f4638",
    "status": "#6f3f1d",
    "sidebar": "#120f0b",
    "border": "#2c261b",
    "keyword": "#d0653b",
    "fn": "#ddb06a",
    "string": "#87ab70",
    "number": "#c66a52",
    "type": "#79a8a2",
    "variable": "#c1b59f",
    "operator": "#a8824e",
    "comment": "#6b5f4d"
  },
  "light": {
    "bg": "#f2eadc",
    "fg": "#2f210e",
    "lineBg": "#ece3d2",
    "lineNo": "#b49d7b",
    "status": "#9d4b12",
    "sidebar": "#e8ddc9",
    "border": "#d2c2a5",
    "keyword": "#8f1f00",
    "fn": "#5a3900",
    "string": "#2e6a2c",
    "number": "#b24724",
    "type": "#0d6378",
    "variable": "#3b2c18",
    "operator": "#755f33",
    "comment": "#847257"
  }
} as const
export type TokenSet = typeof tokens.dark
