// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT
export const tokens = {
  "dark": {
    "bg": "#1e1a12",
    "fg": "#d0c4aa",
    "lineBg": "#262010",
    "lineNo": "#4a4030",
    "status": "#7a4520",
    "sidebar": "#171309",
    "border": "#2e2818",
    "keyword": "#cc8855",
    "fn": "#ddb86a",
    "string": "#90aa78",
    "number": "#cc8868",
    "type": "#c8a06a",
    "variable": "#bfb298",
    "operator": "#a87848",
    "comment": "#6a5e48"
  },
  "light": {
    "bg": "#f8f2e8",
    "fg": "#2c1c08",
    "lineBg": "#f0e8d8",
    "lineNo": "#c0aa88",
    "status": "#b45309",
    "sidebar": "#ede4d4",
    "border": "#ddd0b8",
    "keyword": "#8a3000",
    "fn": "#684000",
    "string": "#385820",
    "number": "#963820",
    "type": "#784418",
    "variable": "#3a2c18",
    "operator": "#906040",
    "comment": "#9a8868"
  }
} as const
export type TokenSet = typeof tokens.dark
